# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SparkPlant' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SparkPlant

  target 'SparkPlant-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SparkPlantTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SparkPlant-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SparkPlant-tvOS

  target 'SparkPlant-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
