# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '8.0'

target 'SparkPlant' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SparkPlant
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

end


