export const NAVIGATE_HOME = 'NAVIGATE_HOME';
export const NAVIGATE_BACK = 'NAVIGATE_BACK';
export const NAVIGATE_RESET_TAGS = 'NAVIGATE_RESET_TAGS';
export const NAVIGATE_RESET_NEWS = 'NAVIGATE_RESET_NEWS';
export const NAVIGATE_RESET_CHECKLISTS = 'NAVIGATE_RESET_CHECKLISTS';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';

export const SET_LOGIN_FACTORY = 'SET_LOGIN_FACTORY';
export const SET_LOGIN_USERNAME = 'SET_LOGIN_USERNAME';
export const SET_LOGIN_PASSWORD = 'SET_LOGIN_PASSWORD';

export const PREVIOUS_LOGIN_SUCCESS = 'PREVIOUS_LOGIN_SUCCESS';
export const PREVIOUS_LOGIN_FAILURE = 'PREVIOUS_LOGIN_FAILURE';
export const PREVIOUS_LOGIN_REQUESTED = 'PREVIOUS_LOGIN_REQUESTED';


export const UNITS_REQUESTED = 'UNITS_REQUESTED';
export const GET_UNITS_SUCCESS = 'GET_UNITS_SUCCES';
export const GET_UNITS_FAILURE = 'GET_UNITS_FAILURE';


export const PLACES_REQUESTED = 'PLACES_REQUESTED';
export const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS';
export const GET_PLACES_FAILURE = 'GET_PLACES_FAILURE';


export const GET_USER_TAGS = 'GET_USER_TAGS';

export const GET_ALL_TAGS = 'GET_ALL_TAGS';

export const USER_TAGS_REQUESTED = 'USER_TAGS_REQUESTED';
export const GET_USER_TAGS_SUCCESS = 'GET_USER_TAGS_SUCCESS';
export const GET_USER_TAGS_FAILURE = 'GET_USER_TAGS_FAILURE';

export const ALL_TAGS_REQUESTED = 'ALL_TAGS_REQUESTED';
export const GET_ALL_TAGS_SUCCESS = 'GET_ALL_TAGS_SUCCESS';
export const GET_ALL_TAGS_FAILURE = 'GET_ALL_TAGS_FAILURE';

export const TAG_PLACES_REQUESTED = "TAG_PLACES_REQUESTED";
export const GET_TAG_PLACES_SUCCESS = "GET_TAG_PLACES_SUCCESS";
export const GET_TAG_PLACES_FAILURE = "GET_TAG_PLACES_FAILURE";

export const TAG_AXIS_REQUESTED = "TAG_AXIS_REQUESTED";
export const GET_TAG_AXIS_SUCCESS = "GET_TAG_AXIS_SUCCESS";
export const GET_TAG_AXIS_FAILURE = "GET_TAG_AXIS_FAILURE";

export const SET_CURRENT_CREATION_PLACE = "SET_CURRENT_CREATION_PLACE";

export const SET_CURRENT_CREATION_PLACE_DETAILS = "SET_CURRENT_CREATION_PLACE_DETAILS";

export const SET_CURRENT_CREATION_PLACE_DETAILS_AUDIO = "SET_CURRENT_CREATION_PLACE_DETAILS_AUDIO";

export const SET_CURRENT_CREATION_PRIMARY_AXIS = "SET_CURRENT_CREATION_PRIMARY_AXIS";

export const SET_CURRENT_CREATION_SECONDARY_AXIS = "SET_CURRENT_CREATION_SECONDARY_AXIS";

export const SET_CURRENT_CREATION_TITLE = "SET_CURRENT_CREATION_TITLE";

export const SET_CURRENT_CREATION_DESCRIPTION = "SET_CURRENT_CREATION_DESCRIPTION";

export const SET_CURRENT_CREATION_DESCRIPTION_AUDIO = "SET_CURRENT_CREATION_DESCRIPTION_AUDIO";

export const TAG_SUPERVISOR_REQUESTED = "TAG_SUPERVISOR_REQUESTED";
export const GET_TAG_SUPERVISOR_SUCCESS = "GET_TAG_SUPERVISOR_SUCCESS";
export const GET_TAG_SUPERVISOR_FAILURE = "GET_TAG_SUPERVISOR_FAILURE";

export const TAG_FOLLOWERS_REQUESTED = "TAG_FOLLOWERS_REQUESTED";
export const GET_TAG_FOLLOWERS_SUCCESS = "GET_TAG_FOLLOWERS_SUCCESS";
export const GET_TAG_FOLLOWERS_FAILURE = "GET_TAG_FOLLOWERS_FAILURE";

export const TAG_CREATE_REQUESTED = "TAG_CREATE_REQUESTED";
export const CREATE_TAG_SUCCESS = "CREATE_TAG_SUCCESS";
export const CREATE_TAG_FAILURE = "CREATE_TAG_FAILURE";

export const SET_CURRENT_TAG = "SET_CURRENT_TAG";

export const SET_TAG_FOLLOWERS = "SET_TAG_FOLLOWERS";

export const TAG_HISTORY_REQUESTED = "TAG_HISTORY_REQUESTED";
export const TAG_HISTORY_SUCCESS = "TAG_HISTORY_SUCCESS";
export const TAG_HISTORY_FAILURE = "TAG_HISTORY_FAILURE";

export const TAG_RESOLVE_REQUESTED = "TAG_RESOLVE_REQUESTED";
export const TAG_RESOLVE_SUCCESS = "TAG_RESOLVE_SUCCESS";
export const TAG_RESOLVE_FAILURE = "TAG_RESOLVE_FAILURE";

export const TAG_CLOSE_REQUESTED = "TAG_CLOSE_REQUESTED";
export const TAG_CLOSE_SUCCESS = "TAG_CLOSE_SUCCESS";
export const TAG_CLOSE_FAILURE = "TAG_CLOSE_FAILURE";

export const TAG_COMMENT_REQUESTED = "TAG_COMMENT_REQUESTED";
export const TAG_COMMENT_SUCCESS = "TAG_COMMENT_SUCCESS";
export const TAG_COMMENT_FAILURE = "TAG_COMMENT_FAILURE";

export const TAG_TRANSFER_USERS_REQUESTED = "TAG_TRANSFER_USERS_REQUESTED";
export const TAG_TRANSFER_USERS_SUCCESS = "TAG_TRANSFER_USERS_SUCCESS";
export const TAG_TRANSFER_USERS_FAILURE = "TAG_TRANSFER_USERS_FAILURE";

export const TAG_TRANSFER_REQUESTED = "TAG_TRANSFER_REQUESTED";
export const TAG_TRANSFER_SUCCESS = "TAG_TRANSFER_SUCCESS";
export const TAG_TRANSFER_FAILURE = "TAG_TRANSFER_FAILURE";

export const TAGS_UPLOAD_MEDIA_REQUESTED = "TAGS_UPLOAD_MEDIA_REQUESTED";
export const TAGS_UPLOAD_MEDIA_SUCCESS = "TAGS_UPLOAD_MEDIA_SUCCESS";
export const TAGS_UPLOAD_MEDIA_FAILURE = "TAGS_UPLOAD_MEDIA_FAILURE";

export const TAGS_UPLOAD_PLACE_AUDIO_REQUESTED = "TAGS_UPLOAD_PLACE_AUDIO_REQUESTED";
export const TAGS_UPLOAD_PLACE_AUDIO_SUCCESS = "TAGS_UPLOAD_PLACE_AUDIO_SUCCESS";
export const TAGS_UPLOAD_PLACE_AUDIO_FAILURE = "TAGS_UPLOAD_PLACE_AUDIO_FAILURE";

export const TAGS_UPLOAD_DESCRIPTION_AUDIO_REQUESTED = "TAGS_UPLOAD_DESCRIPTION_AUDIO_REQUESTED";
export const TAGS_UPLOAD_DESCRIPTION_AUDIO_SUCCESS = "TAGS_UPLOAD_DESCRIPTION_AUDIO_SUCCESS";
export const TAGS_UPLOAD_DESCRIPTION_AUDIO_FAILURE = "TAGS_UPLOAD_DESCRIPTION_AUDIO_FAILURE";

export const TAGS_SEARCH = "TAGS_SEARCH";

export const ADD_TAGS_FILTER = "ADD_TAGS_FILTER";
export const REMOVE_TAGS_FILTER = "REMOVE_TAGS_FILTER";

export const FILTER_TAGS = "FILTER_TAGS";
export const RESET_FILTER_TAGS = "RESET_FILTER_TAGS";
export const FILTER_FULL_TAGS = "FILTER_FULL_TAGS";
export const RESET_FILTER_FULL_TAGS = "RESET_FILTER_FULL_TAGS";

export const RESET_CURRENT_CREATION_TAG = "RESET_CURRENT_CREATION_TAG";

export const SET_TO_RECORD = "SET_TO_RECORD";


export const SET_CURRENT_NEWS = "SET_CURRENT_NEWS";

export const SET_CREATION_VISIBILITY = "SET_CREATION_VISIBILITY";

export const USER_NEWS_REQUESTED = "USER_NEWS_REQUESTED";
export const USER_NEWS_SUCCESS = "USER_NEWS_SUCCESS";
export const USER_NEWS_FAILURE = "USER_NEWS_FAILURE";

export const NEWS_REQUESTED = "NEWS_REQUESTED";
export const NEWS_SUCCESS = "NEWS_SUCCESS";
export const NEWS_FAILURE = "NEWS_FAILURE";

export const WAITING_NEWS_REQUESTED = "WAITING_NEWS_REQUESTED";
export const WAITING_NEWS_SUCCESS = "WAITING_NEWS_SUCCESS";
export const WAITING_NEWS_FAILURE = "WAITING_NEWS_FAILURE";

export const PUBLISH_NEWS_REQUESTED = "PUBLISH_NEWS_REQUESTED";
export const PUBLISH_NEWS_SUCCESS = "PUBLISH_NEWS_SUCCESS";
export const PUBLISH_NEWS_FAILURE = "PUBLISH_NEWS_FAILURE";

export const TRANSFER_NEWS_REQUESTED = "TRANSFER_NEWS_REQUESTED";
export const TRANSFER_NEWS_SUCCESS = "TRANSFER_NEWS_SUCCESS";
export const TRANSFER_NEWS_FAILURE = "TRANSFER_NEWS_FAILURE";

export const DELETE_NEWS_REQUESTED = "DELETE_NEWS_REQUESTED";
export const DELETE_NEWS_SUCCESS = "DELETE_NEWS_SUCCESS";
export const DELETE_NEWS_FAILURE = "DELETE_NEWS_FAILURE";

export const PREPARE_NEWS = "PREPARE_NEWS_SUCCESS";

export const CREATE_NEWS_REQUESTED = "CREATE_NEWS_REQUESTED";
export const CREATE_NEWS_SUCCESS = "CREATE_NEWS_SUCCESS";
export const CREATE_NEWS_FAILURE = "CREATE_NEWS_FAILURE";

export const NEWS_UPLOAD_MEDIA_REQUESTED = "NEWS_UPLOAD_MEDIA_REQUESTED";
export const NEWS_UPLOAD_MEDIA_SUCCESS = "NEWS_UPLOAD_MEDIA_SUCCESS";
export const NEWS_UPLOAD_MEDIA_FAILURE = "NEWS_UPLOAD_MEDIA_FAILURE";

export const NEWS_SEARCH = "NEWS_SEARCH";
export const NEWS_WAITING_SEARCH = "NEWS_WAITING_SEARCH";


export const USER_CHECKLISTS_REQUESTED = "USER_CHECKLISTS_REQUESTED";
export const USER_CHECKLISTS_SUCCESS = "USER_CHECKLISTS_SUCCESS";
export const USER_CHECKLISTS_FAILURE = "USER_CHECKLISTS_FAILURE";

export const CHECKLISTS_TEMPLATES_REQUESTED = "CHECKLISTS_TEMPLATES_REQUESTED";
export const CHECKLISTS_TEMPLATES_SUCCESS = "CHECKLISTS_TEMPLATES_SUCCESS";
export const CHECKLISTS_TEMPLATES_FAILURE = "CHECKLISTS_TEMPLATES_FAILURE";

export const COMPLETE_TASK_REQUESTED = "COMPLETE_TASK_REQUESTED";
export const COMPLETE_TASK_SUCCESS = "COMPLETE_TASK_SUCCESS";
export const COMPLETE_TASK_FAILURE = "COMPLETE_TASK_FAILURE";

export const RESET_TASK_REQUESTED = "RESET_TASK_REQUESTED";
export const RESET_TASK_SUCCESS = "RESET_TASK_SUCCESS";
export const RESET_TASK_FAILURE = "RESET_TASK_FAILURE";

export const COMPLETE_LIST_REQUESTED = "COMPLETE_LIST_REQUESTED";
export const COMPLETE_LIST_SUCCESS = "COMPLETE_LIST_SUCCESS";
export const COMPLETE_LIST_FAILURE = "COMPLETE_LIST_FAILURE";

export const ASSIGN_CHECKLISTS_REQUESTED = "ASSIGN_CHECKLISTS_REQUESTED";
export const ASSIGN_CHECKLISTS_SUCCESS = "ASSIGN_CHECKLISTS_SUCCESS";
export const ASSIGN_CHECKLISTS_FAILURE = "ASSIGN_CHECKLISTS_FAILURE";

export const CHECKLIST_HISTORY_REQUESTED = "CHECKLIST_HISTORY_REQUESTED";
export const CHECKLIST_HISTORY_SUCCESS = "CHECKLIST_HISTORY_SUCCESS";
export const CHECKLIST_HISTORY_FAILURE = "CHECKLIST_HISTORY_FAILURE";

export const FULL_CHECKLIST_HISTORY_REQUESTED = "FULL_CHECKLIST_HISTORY_REQUESTED";
export const FULL_CHECKLIST_HISTORY_SUCCESS = "FULL_CHECKLIST_HISTORY_SUCCESS";
export const FULL_CHECKLIST_HISTORY_FAILURE = "FULL_CHECKLIST_HISTORY_FAILURE";

export const DELETE_USER_CHECKLIST_REQUESTED = 'DELETE_USER_CHECKLIST_REQUESTED';
export const DELETE_USER_CHECKLIST_SUCCESS = 'DELETE_USER_CHECKLIST_SUCCESS';
export const DELETE_USER_CHECKLIST_FAILURE = 'DELETE_USER_CHECKLIST_FAILURE';

export const CREATE_USER_CHECKLIST_REQUESTED = 'CREATE_USER_CHECKLIST_REQUESTED';
export const CREATE_USER_CHECKLIST_SUCCESS = 'CREATE_USER_CHECKLIST_SUCCESS';
export const CREATE_USER_CHECKLIST_FAILURE = 'CREATE_USER_CHECKLIST_FAILURE';

export const CREATE_CHECKLIST_INSTANCE_REQUESTED = 'CREATE_CHECKLIST_INSTANCE_REQUESTED';
export const CREATE_CHECKLIST_INSTANCE_SUCCESS = 'CREATE_CHECKLIST_INSTANCE_SUCCESS';
export const CREATE_CHECKLIST_INSTANCE_FAILURE = 'CREATE_CHECKLIST_INSTANCE_FAILURE';

export const UPDATE_CHECKLIST_INSTANCE_REQUESTED = 'UPDATE_CHECKLIST_INSTANCE_REQUESTED';
export const UPDATE_CHECKLIST_INSTANCE_SUCCESS = 'UPDATE_CHECKLIST_INSTANCE_SUCCESS';
export const UPDATE_CHECKLIST_INSTANCE_FAILURE = 'UPDATE_CHECKLIST_INSTANCE_FAILURE';

export const UPDATE_CHECKLIST_INSTANCE_TASK_REQUESTED = 'UPDATE_CHECKLIST_INSTANCE_TASK_REQUESTED';
export const UPDATE_CHECKLIST_INSTANCE_TASK_SUCCESS = 'UPDATE_CHECKLIST_INSTANCE_TASK_SUCCESS';
export const UPDATE_CHECKLIST_INSTANCE_TASK_FAILURE = 'UPDATE_CHECKLIST_INSTANCE_TASK_FAILURE';

export const SET_CURRENT_CHECKLIST = "SET_CURRENT_CHECKLIST";
export const SET_CURRENT_TEMPLATE = "SET_CURRENT_TEMPLATE";
export const SET_CURRENT_HISTORY = "SET_CURRENT_HISTORY";


export const USER_REQUESTED = "USER_REQUESTED";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const SET_AVAILABILITY_REQUESTED = "SET_AVAILABILITY_REQUESTED";
export const SET_AVAILABILITY_SUCCESS = "SET_AVAILABILITY_SUCCESS";
export const SET_AVAILABILITY_FAILURE = "SET_AVAILABILITY_FAILURE";


export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT";
export const LOGOUT_FAILURE = "LOGOUT";


export const SOLVED_TAGS_REQUESTED = "SOLVED_TAGS_REQUESTED";
export const SOLVED_TAGS_SUCCESS = "SOLVED_TAGS_SUCCESS";
export const SOLVED_TAGS_ERROR = "SOLVED_TAGS_ERROR";

export const UNSOLVED_TAGS_REQUESTED = "UNSOLVED_TAGS_REQUESTED";
export const UNSOLVED_TAGS_SUCCESS = "UNSOLVED_TAGS_SUCCESS";
export const UNSOLVED_TAGS_ERROR = "UNSOLVED_TAGS_ERROR";

//export const baseUrl = "https://sparkplant-api-testing.sooyoos.com";
export const baseUrl = "http://sparkplant-api-develop.sooyoos.com";

export const RESET_LOGIN_ERROR = "RESET_LOGIN_ERROR";

export const RESET_CHARTS = "RESET_CHARTS";
export const RESET_CHECKLISTS = "RESET_CHECKLISTS";
export const RESET_NEWS = "RESET_NEWS";
export const RESET_TAGS = "RESET_TAGS";
export const RESET_USERS = "RESET_USERS";
export const RESET_UTILS = "RESET_UTILS";