export const NAVIGATE_HOME = 'NAVIGATE_HOME';
export const NAVIGATE_BACK = 'NAVIGATE_BACK';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';

export const SET_LOGIN_FACTORY = 'SET_LOGIN_FACTORY';
export const SET_LOGIN_USERNAME = 'SET_LOGIN_USERNAME';
export const SET_LOGIN_PASSWORD = 'SET_LOGIN_PASSWORD';

export const UNITS_REQUESTED = 'UNITS_REQUESTED';
export const GET_UNITS_SUCCESS = 'GET_UNITS_SUCCES';
export const GET_UNITS_FAILURE = 'GET_UNITS_FAILURE';

export const GET_USER_TAGS = 'GET_USER_TAGS';

export const GET_ALL_TAGS = 'GET_ALL_TAGS';

export const USER_TAGS_REQUESTED = 'USER_TAGS_REQUESTED';
export const GET_USER_TAGS_SUCCESS = 'GET_USER_TAGS_SUCCESS';
export const GET_USER_TAGS_FAILURE = 'GET_USER_TAGS_FAILURE';

export const ALL_TAGS_REQUESTED = 'ALL_TAGS_REQUESTED';
export const GET_ALL_TAGS_SUCCESS = 'GET_ALL_TAGS_SUCCESS';
export const GET_ALL_TAGS_FAILURE = 'GET_ALL_TAGS_FAILURE';

export const TAG_PLACES_REQUESTED = "TAG_PLACES_REQUESTED";
export const GET_TAG_PLACES_SUCCESS = "GET_TAG_PLACES_SUCCESS";
export const GET_TAG_PLACES_FAILURE = "GET_TAG_PLACES_FAILURE";

export const TAG_AXIS_REQUESTED = "TAG_AXIS_REQUESTED";
export const GET_TAG_AXIS_SUCCESS = "GET_TAG_AXIS_SUCCESS";
export const GET_TAG_AXIS_FAILURE = "GET_TAG_AXIS_FAILURE";

export const SET_CURRENT_CREATION_PLACE = "SET_CURRENT_CREATION_PLACE";

export const SET_CURRENT_CREATION_PLACE_DETAILS = "SET_CURRENT_CREATION_PLACE_DETAILS";

export const SET_CURRENT_CREATION_PLACE_DETAILS_AUDIO = "SET_CURRENT_CREATION_PLACE_DETAILS_AUDIO";

export const SET_CURRENT_CREATION_PRIMARY_AXIS = "SET_CURRENT_CREATION_PRIMARY_AXIS";

export const SET_CURRENT_CREATION_SECONDARY_AXIS = "SET_CURRENT_CREATION_SECONDARY_AXIS";

export const SET_CURRENT_CREATION_TITLE = "SET_CURRENT_CREATION_TITLE";

export const SET_CURRENT_CREATION_DESCRIPTION = "SET_CURRENT_CREATION_DESCRIPTION";

export const SET_CURRENT_CREATION_DESCRIPTION_AUDIO = "SET_CURRENT_CREATION_DESCRIPTION_AUDIO";

export const TAG_SUPERVISOR_REQUESTED = "TAG_SUPERVISOR_REQUESTED";
export const GET_TAG_SUPERVISOR_SUCCESS = "GET_TAG_SUPERVISOR_SUCCESS";
export const GET_TAG_SUPERVISOR_FAILURE = "GET_TAG_SUPERVISOR_FAILURE";

export const TAG_FOLLOWERS_REQUESTED = "TAG_FOLLOWERS_REQUESTED";
export const GET_TAG_FOLLOWERS_SUCCESS = "GET_TAG_FOLLOWERS_SUCCESS";
export const GET_TAG_FOLLOWERS_FAILURE = "GET_TAG_FOLLOWERS_FAILURE";

export const TAG_CREATE_REQUESTED = "TAG_CREATE_REQUESTED";
export const CREATE_TAG_SUCCESS = "CREATE_TAG_SUCCESS";
export const CREATE_TAG_FAILURE = "CREATE_TAG_FAILURE";

export const SET_CURRENT_TAG = "SET_CURRENT_TAG";

export const TAG_HISTORY_REQUESTED = "TAG_HISTORY_REQUESTED";
export const TAG_HISTORY_SUCCESS = "TAG_HISTORY_SUCCESS";
export const TAG_HISTORY_FAILURE = "TAG_HISTORY_FAILURE";

export const TAG_RESOLVE_REQUESTED = "TAG_RESOLVE_REQUESTED";
export const TAG_RESOLVE_SUCCESS = "TAG_RESOLVE_SUCCESS";
export const TAG_RESOLVE_FAILURE = "TAG_RESOLVE_FAILURE";

export const TAG_CLOSE_REQUESTED = "TAG_CLOSE_REQUESTED";
export const TAG_CLOSE_SUCCESS = "TAG_CLOSE_SUCCESS";
export const TAG_CLOSE_FAILURE = "TAG_CLOSE_FAILURE";

export const TAG_COMMENT_REQUESTED = "TAG_COMMENT_REQUESTED";
export const TAG_COMMENT_SUCCESS = "TAG_COMMENT_SUCCESS";
export const TAG_COMMENT_FAILURE = "TAG_COMMENT_FAILURE";

export const TAG_TRANSFER_USERS_REQUESTED = "TAG_TRANSFER_USERS_REQUESTED";
export const TAG_TRANSFER_USERS_SUCCESS = "TAG_TRANSFER_USERS_SUCCESS";
export const TAG_TRANSFER_USERS_FAILURE = "TAG_TRANSFER_USERS_FAILURE";

export const TAG_TRANSFER_REQUESTED = "TAG_TRANSFER_REQUESTED";
export const TAG_TRANSFER_SUCCESS = "TAG_TRANSFER_SUCCESS";
export const TAG_TRANSFER_FAILURE = "TAG_TRANSFER_FAILURE";


export const SET_CURRENT_NEWS = "SET_CURRENT_NEWS";

export const SET_CREATION_VISIBILITY = "SET_CREATION_VISIBILITY";

export const USER_NEWS_REQUESTED = "USER_NEWS_REQUESTED";
export const USER_NEWS_SUCCESS = "USER_NEWS_SUCCESS";
export const USER_NEWS_FAILURE = "USER_NEWS_FAILURE";

export const WAITING_NEWS_REQUESTED = "WAITING_NEWS_REQUESTED";
export const WAITING_NEWS_SUCCESS = "WAITING_NEWS_SUCCESS";
export const WAITING_NEWS_FAILURE = "WAITING_NEWS_FAILURE";

export const PUBLISH_NEWS_REQUESTED = "PUBLISH_NEWS_REQUESTED";
export const PUBLISH_NEWS_SUCCESS = "PUBLISH_NEWS_SUCCESS";
export const PUBLISH_NEWS_FAILURE = "PUBLISH_NEWS_FAILURE";

export const TRANSFER_NEWS_REQUESTED = "TRANSFER_NEWS_REQUESTED";
export const TRANSFER_NEWS_SUCCESS = "TRANSFER_NEWS_SUCCESS";
export const TRANSFER_NEWS_FAILURE = "TRANSFER_NEWS_FAILURE";

export const DELETE_NEWS_REQUESTED = "DELETE_NEWS_REQUESTED";
export const DELETE_NEWS_SUCCESS = "DELETE_NEWS_SUCCESS";
export const DELETE_NEWS_FAILURE = "DELETE_NEWS_FAILURE";

export const PREPARE_NEWS = "PREPARE_NEWS_SUCCESS";

export const CREATE_NEWS_REQUESTED = "CREATE_NEWS_REQUESTED";
export const CREATE_NEWS_SUCCESS = "CREATE_NEWS_SUCCESS";
export const CREATE_NEWS_FAILURE = "CREATE_NEWS_FAILURE";